name = "docs"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
min_version = "0.164.0" # If changed, update hugo.toml

[author]
  name = "ItalyPaleAle"

[features]
  [features.sharedAssets]
    useResourceCacheWhen = "fallback"
